### PR TITLE
Fix #43. Add `string` options to output json object string.

### LINKED ISSUE #43: TypeError: text.forEach is not a function
Hi, I want to use `json-loader` with `ExtractTextPlugin` like this config:

```js
rule: {
  test: /\.json$/,
  loader: ExtractJSON.extract({
    loader: [{
      loader: 'json-loader'
    }]
  })
}
```

That was throw this error:

```sh
ERROR in ./src/index.json
    Module build failed: TypeError: text.forEach is not a function
        at Object.<anonymous> (\node_modules\extract-text-webpack-plugin\loader.js:109:10)
        at Compiler.<anonymous> (\node_modules\webpack\lib\Compiler.js:280:10)
        at \node_modules\webpack\lib\Compiler.js:480:13
        ...
```

I change the json-loader return value as:

```js
// json-loader/index.js

return "module.exports = " + '`' + JSON.stringify(value, undefined, "\t") + '`' + ";";
```

It's works fine, but I think it's not a good idea. Anything help for this problem ?

Thanks :)

### PR DESCRIPTION
**Pull request by yuffiy**
output json object as string.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,10 +1,15 @@
...
+var loaderUtils = require('loader-utils');
+
 module.exports = function(source) {
-	this.cacheable && this.cacheable();
-	var value = typeof source === "string" ? JSON.parse(source) : source;
-	this.value = [value];
-	return "module.exports = " + JSON.stringify(value) + ";";
+    this.cacheable && this.cacheable();    
+    var value = typeof source === "string" ? JSON.parse(source) : source;
+    this.value = [value];
```
Comment (michael-ciniawsky) [inline index.js]: Unrelated, but this can be removed since it was needed in webpack =< v0.8.0 only

File: README.md [hunk 2]
```diff
@@ -60,6 +60,17 @@ import json from 'file.json';
 import json from 'json-loader!file.json';
 ```
 
+
+
+### Options
+
+#### `string`
```
Comment (michael-ciniawsky) [inline README.md]: `string` => `stringify`  for naming consistency with JSON.stringify

File: index.js [hunk 3]
```diff
@@ -1,10 +1,15 @@
...
+    var query = loaderUtils.getOptions(this) || {}
+    if(query.string)
+	return "module.exports = `" + JSON.stringify(value) + "`;";
```
Comment (michael-ciniawsky) [inline index.js]: Please put it on the same line as the `if` statement or add the `{}`  😛

File: README.md [hunk 4]
```diff
@@ -60,6 +60,17 @@ import json from 'file.json';
 import json from 'json-loader!file.json';
 ```
 
+
+
+### Options
+
+#### `string`
+
+By default, the json-loader will output the json object, set this query parameter to 'ture' can output the json object as a string, e.g. `require('json-loader?string!../index.json')`. It's useful work with `ExtractTextPlugin`
```
Comment (bebraw) [inline README.md]: `true` over `ture`.

Comment (bebraw) [inline README.md]: Tune the last sentence too.

File: index.js (hunk 1 above)
Comment (bebraw) [inline index.js]: Yeah. `this.cacheable` isn't needed either.

File: index.js (hunk 3 above)
Comment (bebraw) [inline index.js]: Sidenote - webpack-defaults will catch these.

File: index.js [hunk 5]
```diff
@@ -1,10 +1,15 @@
...
+    return "module.exports = " + JSON.stringify(value) + ";";
```
Comment (bebraw) [inline index.js]: Do we want to go webpack 2 here? Separate PR would be probably better for that change, though.

File: index.js [hunk 6]
```diff
@@ -1,10 +1,14 @@
...
+
 module.exports = function(source) {
-	this.cacheable && this.cacheable();
-	var value = typeof source === "string" ? JSON.parse(source) : source;
-	this.value = [value];
-	return "module.exports = " + JSON.stringify(value) + ";";
+    var value = typeof source === "string" ? JSON.parse(source) : source;
+    this.value = [value];
+    var query = loaderUtils.getOptions(this) || {};
+    var outprefix = this.version && this.version >= 2 ? "export default " : "module.exports = ";
```
Comment (michael-ciniawsky) [inline index.js]: `query` => `options`

```js
const options = loaderUtils.getOptions(this) || {}

const value = typeof source === "string" ? JSON.parse(source) : source

value = options.stringify ? `${JSON.stringify(value)}` : JSON.stringify(value)

const module = this.version >= 2  ? `export default ${value}` : `module.exports = ${value}` 

return module
```

Comment (yuffiy) [inline index.js]: ❤️

**Comment by michael-ciniawsky** [comment]
@yuffiy Thx sry for the nitpicking 😛

**Comment by yuffiy** [comment]
@michael-ciniawsky 
😘
